// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/google/uuid"
)

type Pelicula struct {
	Codigo            uuid.UUID
	Nombre            string
	ClasificacionEdad int32
}

type Sala struct {
	Codigo   uuid.UUID
	Nombre   string
	Pelicula uuid.UUID
}
